# Generated by Django 3.1.2 on 2025-12-22 07:02

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=19, unique=True)),
                ('card_holder_name', models.CharField(max_length=100)),
                ('expiry_month', models.CharField(max_length=2)),
                ('expiry_year', models.CharField(max_length=4)),
                ('cvv', models.CharField(max_length=4)),
                ('card_type', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('amex', 'American Express'), ('discover', 'Discover')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked'), ('expired', 'Expired'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=12)),
                ('daily_limit', models.DecimalField(decimal_places=2, default=Decimal('5000.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mock_bank_cards',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_number', models.CharField(max_length=19)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('decline_reason', models.CharField(blank=True, choices=[('insufficient_funds', 'Insufficient Funds'), ('invalid_card', 'Invalid Card'), ('expired_card', 'Expired Card'), ('blocked_card', 'Blocked Card'), ('limit_exceeded', 'Daily Limit Exceeded'), ('invalid_cvv', 'Invalid CVV'), ('network_error', 'Network Error')], max_length=50, null=True)),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='banking.bankcard')),
            ],
            options={
                'db_table': 'mock_payment_transactions',
            },
        ),
        migrations.AddIndex(
            model_name='bankcard',
            index=models.Index(fields=['card_number'], name='mock_bank_c_card_nu_092542_idx'),
        ),
        migrations.AddIndex(
            model_name='bankcard',
            index=models.Index(fields=['status'], name='mock_bank_c_status_ab7b0e_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['card_number'], name='mock_paymen_card_nu_7f04c5_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['status'], name='mock_paymen_status_b1d5e4_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['reference_id'], name='mock_paymen_referen_823fa1_idx'),
        ),
    ]
