# Generated by Django 3.1.2 on 2025-12-18 09:03

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points_earned', models.PositiveIntegerField(default=0)),
                ('current_points_balance', models.PositiveIntegerField(default=0)),
                ('lifetime_spending', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('tier_qualification_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyTier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('min_points_required', models.PositiveIntegerField(default=0)),
                ('points_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Multiplier for points earned (e.g., 1.5 for 50% bonus)', max_digits=3)),
                ('redemption_bonus', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Bonus when redeeming points (e.g., 1.1 for 10% bonus value)', max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['min_points_required'],
            },
        ),
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('earn', 'Earn Points'), ('redeem', 'Redeem Points'), ('expire', 'Points Expired'), ('bonus', 'Bonus Points'), ('adjustment', 'Manual Adjustment')], max_length=20)),
                ('points_amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loyalty.loyaltyaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='loyaltyaccount',
            name='current_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='loyalty.loyaltytier'),
        ),
        migrations.AddField(
            model_name='loyaltyaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='pointstransaction',
            index=models.Index(fields=['account', 'transaction_type'], name='loyalty_poi_account_50fe45_idx'),
        ),
        migrations.AddIndex(
            model_name='pointstransaction',
            index=models.Index(fields=['status', 'created_at'], name='loyalty_poi_status_577da0_idx'),
        ),
        migrations.AddIndex(
            model_name='pointstransaction',
            index=models.Index(fields=['expires_at'], name='loyalty_poi_expires_6619dd_idx'),
        ),
        migrations.AddIndex(
            model_name='pointstransaction',
            index=models.Index(fields=['reference_id'], name='loyalty_poi_referen_e9fa9e_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltyaccount',
            index=models.Index(fields=['user'], name='loyalty_loy_user_id_170e64_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltyaccount',
            index=models.Index(fields=['current_tier'], name='loyalty_loy_current_1a70d7_idx'),
        ),
    ]
